services:
  postgres:
    image: postgres:16-alpine
    container_name: vaga-garantida-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vaga
      POSTGRES_PASSWORD: vaga
      POSTGRES_DB: vaga_garantida
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
