[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build -w @vaga-garantida/web"

[build.env]
NIXPACKS_NODE_VERSION = "20"

[deploy]
startCommand = "npm run start -w @vaga-garantida/web"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
